1.自身の取り組む通し課題を1つ選択する
　キノコを識別するデータセットを選択

In [117]:
#使用するライブラリのインポート
import pandas as pd
import numpy as np
from IPython.display import display
#from dateutil.parser import parse
import matplotlib.pyplot as plt
from sklearn.linear_model import LogisticRegression
from sklearn.linear_model import LinearRegression
from sklearn.metrics import classification_report
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score


#データセットの読み込み
df_data = pd.read_csv("mushrooms.csv")

#データセットの項目を表示
print(df_data.columns)

#データセットの一部を表示（先頭と末尾）
display(df_data.head())
display(df_data.tail())

Index(['class', 'cap-shape', 'cap-surface', 'cap-color', 'bruises', 'odor',
       'gill-attachment', 'gill-spacing', 'gill-size', 'gill-color',
       'stalk-shape', 'stalk-root', 'stalk-surface-above-ring',
       'stalk-surface-below-ring', 'stalk-color-above-ring',
       'stalk-color-below-ring', 'veil-type', 'veil-color', 'ring-number',
       'ring-type', 'spore-print-color', 'population', 'habitat'],
      dtype='object')

,class,cap-shape,cap-surface,cap-color,bruises,odor,gill-attachment,gill-spacing,gill-size,gill-color,...,stalk-surface-below-ring,stalk-color-above-ring,stalk-color-below-ring,veil-type,veil-color,ring-number,ring-type,spore-print-color,population,habitat
0,p,x,s,n,t,p,f,c,n,k,...,s,w,w,p,w,o,p,k,s,u
1,e,x,s,y,t,a,f,c,b,k,...,s,w,w,p,w,o,p,n,n,g
2,e,b,s,w,t,l,f,c,b,n,...,s,w,w,p,w,o,p,n,n,m
3,p,x,y,w,t,p,f,c,n,n,...,s,w,w,p,w,o,p,k,s,u
4,e,x,s,g,f,n,f,w,b,k,...,s,w,w,p,w,o,e,n,a,g

,class,cap-shape,cap-surface,cap-color,bruises,odor,gill-attachment,gill-spacing,gill-size,gill-color,...,stalk-surface-below-ring,stalk-color-above-ring,stalk-color-below-ring,veil-type,veil-color,ring-number,ring-type,spore-print-color,population,habitat
8119,e,k,s,n,f,n,a,c,b,y,...,s,o,o,p,o,o,p,b,c,l
8120,e,x,s,n,f,n,a,c,b,y,...,s,o,o,p,n,o,p,b,v,l
8121,e,f,s,n,f,n,a,c,b,n,...,s,o,o,p,o,o,p,b,c,l
8122,p,k,y,n,f,y,f,c,n,b,...,k,w,w,p,w,o,e,w,v,l
8123,e,x,s,n,f,n,a,c,b,y,...,s,o,o,p,o,o,p,o,c,l

2.目的変数と説明変数の関係を確認するためのグラフを作成する<br>
　クロス集計を使用し、各説明変数と目的変数の関係を確認<br>
　目的変数　：　class （e ：食べれる,　p : 毒）

In [118]:
for col in df_data.columns:
    if col=="class":
        continue
    print(col)
    df_c = pd.crosstab(index=df_data["class"], columns=df_data[col],margins=True)
    display(df_c)

cap-shape

cap-shape    b  c     f    k   s     x   All
class
e          404  0  1596  228  32  1948  4208
p           48  4  1556  600   0  1708  3916
All        452  4  3152  828  32  3656  8124

cap-surface

cap-surface     f  g     s     y   All
class
e            1560  0  1144  1504  4208
p             760  4  1412  1740  3916
All          2320  4  2556  3244  8124

cap-color

cap-color    b   c     e     g     n    p   r   u     w     y   All
class
e           48  32   624  1032  1264   56  16  16   720   400  4208
p          120  12   876   808  1020   88   0   0   320   672  3916
All        168  44  1500  1840  2284  144  16  16  1040  1072  8124

bruises

bruises     f     t   All
class
e        1456  2752  4208
p        3292   624  3916
All      4748  3376  8124

odor

odor     a    c     f    l   m     n    p    s    y   All
class
e      400    0     0  400   0  3408    0    0    0  4208
p        0  192  2160    0  36   120  256  576  576  3916
All    400  192  2160  400  36  3528  256  576  576  8124

gill-attachment

gill-attachment    a     f   All
class
e                192  4016  4208
p                 18  3898  3916
All              210  7914  8124

gill-spacing

gill-spacing     c     w   All
class
e             3008  1200  4208
p             3804   112  3916
All           6812  1312  8124

gill-size

gill-size     b     n   All
class
e          3920   288  4208
p          1692  2224  3916
All        5612  2512  8124

gill-color

gill-color     b   e    g    h    k     n   o     p   r    u     w   y   All
class
e              0  96  248  204  344   936  64   852   0  444   956  64  4208
p           1728   0  504  528   64   112   0   640  24   48   246  22  3916
All         1728  96  752  732  408  1048  64  1492  24  492  1202  86  8124

stalk-shape

stalk-shape     e     t   All
class
e            1616  2592  4208
p            1900  2016  3916
All          3516  4608  8124

stalk-root

stalk-root     ?     b    c     e    r   All
class
e            720  1920  512   864  192  4208
p           1760  1856   44   256    0  3916
All         2480  3776  556  1120  192  8124

stalk-surface-above-ring

stalk-surface-above-ring    f     k     s   y   All
class
e                         408   144  3640  16  4208
p                         144  2228  1536   8  3916
All                       552  2372  5176  24  8124

stalk-surface-below-ring

stalk-surface-below-ring    f     k     s    y   All
class
e                         456   144  3400  208  4208
p                         144  2160  1536   76  3916
All                       600  2304  4936  284  8124

stalk-color-above-ring

stalk-color-above-ring    b   c   e    g    n    o     p     w  y   All
class
e                         0   0  96  576   16  192   576  2752  0  4208
p                       432  36   0    0  432    0  1296  1712  8  3916
All                     432  36  96  576  448  192  1872  4464  8  8124

stalk-color-below-ring

stalk-color-below-ring    b   c   e    g    n    o     p     w   y   All
class
e                         0   0  96  576   64  192   576  2704   0  4208
p                       432  36   0    0  448    0  1296  1680  24  3916
All                     432  36  96  576  512  192  1872  4384  24  8124

veil-type

veil-type     p   All
class
e          4208  4208
p          3916  3916
All        8124  8124

veil-color

veil-color   n   o     w  y   All
class
e           96  96  4016  0  4208
p            0   0  3908  8  3916
All         96  96  7924  8  8124

ring-number

ring-number   n     o    t   All
class
e             0  3680  528  4208
p            36  3808   72  3916
All          36  7488  600  8124

ring-type

ring-type     e   f     l   n     p   All
class
e          1008  48     0   0  3152  4208
p          1768   0  1296  36   816  3916
All        2776  48  1296  36  3968  8124

spore-print-color

spore-print-color   b     h     k     n   o   r   u     w   y   All
class
e                  48    48  1648  1744  48   0  48   576  48  4208
p                   0  1584   224   224   0  72   0  1812   0  3916
All                48  1632  1872  1968  48  72  48  2388  48  8124

population

population    a    c    n     s     v     y   All
class
e           384  288  400   880  1192  1064  4208
p             0   52    0   368  2848   648  3916
All         384  340  400  1248  4040  1712  8124

habitat

habitat     d     g    l    m     p    u    w   All
class
e        1880  1408  240  256   136   96  192  4208
p        1268   740  592   36  1008  272    0  3916
All      3148  2148  832  292  1144  368  192  8124

3．目的変数を説明するのに有効そうな説明変数を見つける。<br>
　　odor, spore-print-colorでうまく判別できるのではないかと考えられる。<br>
　　　理由：説明変数の各値でclassのe/pの分類ができているように見える。

4.欠測値と異常値を確認し、適切に処理する。<br>
　欠測値の確認としてpandasの関数を使用する。<br>
<br>
　また、クロス集計から下記項目がデータとして不適切だと考えられる。<br>
　・"veil-type"は値が一つしかないため削除<br>
　・"stalk-root"に"?"が含まれているため置換する。<br>

In [119]:
pd.DataFrame(df_data.isnull().sum(), columns=["num of missing"])

                          num of missing
class                                  0
cap-shape                              0
cap-surface                            0
cap-color                              0
bruises                                0
odor                                   0
gill-attachment                        0
gill-spacing                           0
gill-size                              0
gill-color                             0
stalk-shape                            0
stalk-root                             0
stalk-surface-above-ring               0
stalk-surface-below-ring               0
stalk-color-above-ring                 0
stalk-color-below-ring                 0
veil-type                              0
veil-color                             0
ring-number                            0
ring-type                              0
spore-print-color                      0
population                             0
habitat                                0

欠測値は確認されなかった。

In [120]:
#？の置換
df_data = df_data.replace('?', 'n')
#データの削除
df_data = df_data.drop(['veil-type'], axis = 1)

5.DAY1で学んだアルゴリズムを利用する。<br>
　この問題は、classのe(=食用)、p(=毒)を分類する問題のため<br>
　ロジスティック回帰を使用する。<br>
<br>
　また、全て質的変数のためダミー変数に置き換える。<br>
　今回は目的変数：classと説明変数：spore-print-color, odorのみ<br>

In [121]:
#目的変数classをダミー変数に置き換える
df_data['cls'] = df_data['class'].astype(str).map(lambda x:'class_'+ x)
df_en_1 = pd.concat([df_data, pd.get_dummies(df_data['cls'])], axis=1)
df_en_1 = df_en_1.drop(['class', 'cls'], axis=1)

#spore-print-colorをダミー変数に置き換える
df_en_1['spc']= df_en_1['spore-print-color'].astype(str).map(lambda x:'spc_'+ x)
df_en_2 = pd.concat([df_en_1, pd.get_dummies(df_en_1['spc'])], axis=1)
df_en_2 = df_en_2.drop(['spore-print-color','spc' ], axis=1)

#odorをダミー変数に置き換える
df_en_2['odr'] = df_en_2['odor'].astype(str).map(lambda x:'odor_' + x)
df_en_3 = pd.concat([df_en_2, pd.get_dummies(df_en_2['odr'])], axis=1)
df_en_3 = df_en_3.drop(['odor', 'odr'], axis=1)

#使用しないデータ項目を削除
df_fin = df_en_3.drop(['cap-shape', 'cap-surface', 'cap-color', 'bruises','gill-attachment', 'gill-spacing', 
                       'gill-size', 'gill-color','stalk-shape', 'stalk-root', 'stalk-surface-above-ring','stalk-surface-below-ring', 
                       'stalk-color-above-ring','stalk-color-below-ring', 'veil-color', 'ring-number','ring-type', 'population', 
                       'habitat'], axis=1)

選択した説明変数が適切かどうか確認する（相関係数、多重共線性）<br>
・相関係数を確認し、class_pに対して高い相関があるか確認

In [123]:
display(df_fin.corr().style.background_gradient().format('{:.2f}'))

相関の低かった項目を削除

In [124]:
df_fin = df_fin.drop(['class_e', 'spc_u', 'spc_o', 'spc_y','spc_b', 'odor_m', 'spc_r', 'odor_c', 'odor_p'], axis = 1)
display(df_fin.head())

,class_p,spc_h,spc_k,spc_n,spc_w,odor_a,odor_f,odor_l,odor_n,odor_s,odor_y
0,1,0,1,0,0,0,0,0,0,0,0
1,0,0,0,1,0,1,0,0,0,0,0
2,0,0,0,1,0,0,0,1,0,0,0
3,1,0,1,0,0,0,0,0,0,0,0
4,0,0,0,1,0,0,0,0,1,0,0

多重共線性が生じているか確認

In [125]:
dfd = df_fin.drop(['class_p'], axis=1)

for cname in dfd.columns:
    y=dfd[cname]
    X=dfd.drop(cname, axis=1)
    
    regr = LinearRegression(fit_intercept=True)
    regr.fit(X,y)
    rsquared = regr.score(X,y)
    print(cname, ":", 1/(1-np.power(rsquared,2)))

spc_h : 4.9024488219623255
spc_k : 3.409977443201772
spc_n : 3.499069138636717
spc_w : 4.701943080264438
odor_a : 1.2229805171908001
odor_f : 4.227156301519715
odor_l : 1.2229805171908001
odor_n : 2.6671055866393667
odor_s : 1.724845562456227
odor_y : 1.7248455624562267

多重共線性なし

6.混同行列を作成し、Accuracy、Recall、Precisionを求める。

In [126]:
#目的変数のclass_p(毒)
y = df_fin.class_p
#目的変数を除いた説明変数
X = df_fin.drop(['class_p'], axis=1)

#学習データとテストデータを分割する
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = 0.2, random_state=42)

#ロジスティック回帰のインスタンス作成
lr = LogisticRegression()

#学習データでモデル作成
lr.fit(X_train, y_train)

print(lr.coef_, lr.intercept_)

#テストデータで評価
y_pred = lr.predict(X_test)

#評価結果の表示
print("Accuracy :", accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[-1.2106085  -3.18045021 -3.22114685 -1.08767479 -7.15557338  2.02536574
  -7.13527086 -7.21872536  1.18440713  1.16348453]] [5.88220948]
Accuracy : 0.9846153846153847
             precision    recall  f1-score   support

          0       0.97      1.00      0.99       843
          1       1.00      0.97      0.98       782

avg / total       0.99      0.98      0.98      1625